# Generated by Django 3.2.8 on 2021-11-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='country',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
